report:
  title: "大模型前沿技术跟踪报告"
  issue: "2025年第14期"
  org: "科信司人工智能技术研究小组"
  date: "2025-08-10"
  output: "output/report10.docx"


sources:
  - url: "3"
    category: "技术前沿"
  - url: "https://mp.weixin.qq.com/s?__biz=Mzg2Mjg1NjExNA==&mid=2247607011&idx=2&sn=c2dc322b5394d10038ec01252f3cc2bf"
    category: "技术前沿"
  - url: "https://mp.weixin.qq.com/s/kPE0UikbaerFN-47LA4jRQ"
    category: "技术前沿"
  - url: "https://mp.weixin.qq.com/s?__biz=Mzk2ODAyODU2Nw==&mid=2247487562&idx=1&sn=c669649fed46a859f43e4b66eef54d86"
    category: "产业动态"
  - url: "https://mp.weixin.qq.com/s?__biz=Mzg5NDY0ODA2Mg==&mid=2247484311&idx=2&sn=c08db184311dcbf4d99a413f3a089bfc"
    category: "产业动态"
  - url: "https://mp.weixin.qq.com/s/jetdR7cy_jVKILi8wAWdZA"
    category: "产业动态"
  - url: "https://mp.weixin.qq.com/s?__biz=Mzk3NTE5ODAwMA==&mid=2247483896&idx=3&sn=f76eb8b5b3bcd5a262787adb39ee64b5"
    category: "政策法规"
  - url: "https://mp.weixin.qq.com/s?__biz=MzE5MTU3MzUwNA==&mid=2247484244&idx=1&sn=b9f800f2f3561d5a8853124fc562f95d"
    category: "政策法规"
  - url: "https://mp.weixin.qq.com/s?__biz=MzAxMjIwMjQyMQ==&mid=2650520279&idx=2&sn=f5ccbdbd8fe6b26d16a6bf6934445610"
    category: "应用实例"
  - url: "https://mp.weixin.qq.com/s?__biz=MzkzNzk1OTAxMA==&mid=2247484415&idx=1&sn=048ee7ca9c6c31dc2bb6e065255c959e"
    category: "应用实例"
  - url: "https://mp.weixin.qq.com/s?__biz=Mzk0MjAyMTMwOA==&mid=2247490049&idx=1&sn=7f958d89997772c4b4ecc47bbe273006"
    category: "应用实例"